apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  restartPolicy: Always
  containers:
  - name: cuda-test
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["/bin/bash", "-c"]
    args:
    - |
      while true; do
        nvidia-smi
        echo "---"
        sleep 10
      done
    resources:
      limits:
        nvidia.com/gpu: 1
