apiVersion: v1
kind: Service
metadata:
  name: color-svc
spec:
  type: LoadBalancer
  selector:
    app: color-api
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: color-svc-np
spec:
  type: NodePort
  selector:
    app: color-api
  ports:
    - port: 80
      targetPort: 80
