apiVersion: v1
kind: Pod
metadata:
  name: red-color-api
  labels:
    app: red-color-api
spec:
  containers:
    - name: color-api
      image: lmacademy/color-api:1.3.0
      envFrom:
        - configMapRef:
            name: red-config
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 80
